import logging
loginLogger = logging.getLogger("loginregist")
loginLogger.setLevel(logging.DEBUG)
fileHandler = logging.FileHandler("loginregist.txt", encoding="utf8")
fileHandler.setLevel(logging.ERROR)
fileformater = logging.Formatter("%(name)s-%(levelno)s-%(lineno)d-%(asctime)s-%(message)s")
fileHandler.setFormatter(fileformater)
streamHandler = logging.StreamHandler()
streamHandler.setLevel(logging.INFO)
streamHandler.setFormatter(fileformater)
loginLogger.addHandler(fileHandler)
loginLogger.addHandler(streamHandler)
loginLogger.info("info111")
loginLogger.error("error111")
loginLogger.debug("debug...")
loginLogger.warning("warn111")
